apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drprepper
  name: drprepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drprepper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drprepper
    spec:
      containers:
      - image: nyk1ben/drprepper
        name: drprepper
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drprepper
  name: drprepper
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: drprepper
  type: ClusterIP
status:
  loadBalancer: {}
